export const deck = [
    "Ephara, God of the Polis",
    "Angel of the Dire Hour",
    "Arcane Laboratory",
    "Archon of Emeria",
    "As Foretold",
    "Azorius Chancery",
    "Brineborn Cutthroat",
    "Cathar Commando",
    "Cloud Key",
    "Command Tower",
    "Containment Priest",
    "Deafening Silence",
    "Dimensional Infiltrator",
    "Dust Elemental",
    "Eidolon of Rhetoric",
    "Errant and Giada",
    "Exotic Orchard",
    "Faerie Vandal",
    "Githzerai Monk",
    "Grand Arbiter Augustin IV",
    "Hullbreaker Horror",
    "Inniaz, the Gale Force",
    "Island",
    "Jazal Goldmane",
    "Jeskai Barricade",
    "Kangee's Lieutenant",
    "Kefnet's Monument",
    "Lofty Denial",
    "Loyal Gryff",
    "Malcolm, Alluring Scoundrel",
    "Mirror Entity",
    "Mizzium Meddler",
    "Moderation",
    "Myriad Landscape",
    "Nadir Kraken",
    "Naiad of Hidden Coves",
    "Nebelgast Herald",
    "Nimble Obstructionist",
    "Nimbus Maze",
    "Oketra's Monument",
    "Overcharged Amalgam",
    "Perplexing Chimera",
    "Pestermite",
    "Phyrexian Censor",
    "Plains",
    "Port Town",
    "Prairie Stream",
    "Profaner of the Dead",
    "Quickling",
    "Rescuer Chwinga",
    "Rule of Law",
    "Saprazzan Legate",
    "Semblance Anvil",
    "Sigrid, God-Favored",
    "Silumgar Sorcerer",
    "Sister of Silence",
    "Skybridge Towers",
    "Skycloud Expanse",
    "Spectral Sailor",
    "Spell Queller",
    "Spirit of the Labyrinth",
    "Step Through",
    "Stonecloaker",
    "Sunscape Familiar",
    "Temple of Enlightenment",
    "Temple of the False God",
    "Thistledown Liege",
    "Thraben Watcher",
    "Threnody Singer",
    "Thryx, the Sudden Storm",
    "Thunderclap Wyvern",
    "Unified Will",
    "Vedalken Aethermage",
    "Victory Chimes",
    "Voidmage Husher",
    "Warden of Evos Isle",
    "Watcher of the Spheres",
    "Wavebreak Hippocamp",
    "Whitemane Lion",
];
